export const sampleData = [
  { id: 1, name: "John", country: "USA", age: 37, hireDate: "2020-01-15", department: "Sales", jobTitle: "Manager" },
  { id: 2, name: "Jane", country: "Canada", age: 29, hireDate: "2019-03-12", department: "Marketing", jobTitle: "Specialist" },
  { id: 3, name: "Alice", country: "UK", age: 34, hireDate: "2018-07-23", department: "HR", jobTitle: "Coordinator" },
  { id: 4, name: "Bob", country: "Australia", age: 41, hireDate: "2017-11-05", department: "IT", jobTitle: "Developer" },
  { id: 5, name: "Charlie", country: "Germany", age: 28, hireDate: "2021-02-18", department: "Finance", jobTitle: "Analyst" },
  { id: 6, name: "Diana", country: "France", age: 32, hireDate: "2016-09-30", department: "Operations", jobTitle: "Supervisor" },
  { id: 7, name: "Eve", country: "Japan", age: 26, hireDate: "2020-12-01", department: "Sales", jobTitle: "Representative" },
  { id: 8, name: "Frank", country: "Italy", age: 39, hireDate: "2015-04-22", department: "Marketing", jobTitle: "Manager" },
  { id: 9, name: "Grace", country: "Spain", age: 31, hireDate: "2019-08-14", department: "HR", jobTitle: "Assistant" },
  { id: 10, name: "Hank", country: "Netherlands", age: 45, hireDate: "2014-06-17", department: "IT", jobTitle: "Architect" },
  { id: 11, name: "Ivy", country: "Sweden", age: 27, hireDate: "2021-10-25", department: "Finance", jobTitle: "Consultant" },
  { id: 12, name: "Jack", country: "Norway", age: 36, hireDate: "2018-01-09", department: "Operations", jobTitle: "Manager" },
  { id: 13, name: "Karen", country: "Denmark", age: 33, hireDate: "2017-05-13", department: "Sales", jobTitle: "Executive" },
  { id: 14, name: "Leo", country: "Finland", age: 30, hireDate: "2020-03-19", department: "Marketing", jobTitle: "Coordinator" },
  { id: 15, name: "Mona", country: "Switzerland", age: 38, hireDate: "2016-08-27", department: "HR", jobTitle: "Manager" },
  { id: 16, name: "Nina", country: "Belgium", age: 29, hireDate: "2019-11-11", department: "IT", jobTitle: "Engineer" },
  { id: 17, name: "Oscar", country: "Austria", age: 42, hireDate: "2015-02-05", department: "Finance", jobTitle: "Director" },
  { id: 18, name: "Paul", country: "Ireland", age: 35, hireDate: "2018-06-21", department: "Operations", jobTitle: "Specialist" },
  { id: 19, name: "Quinn", country: "Portugal", age: 28, hireDate: "2021-09-14", department: "Sales", jobTitle: "Consultant" },
  { id: 20, name: "Rita", country: "Greece", age: 37, hireDate: "2017-12-03", department: "Marketing", jobTitle: "Executive" },
];
